version: '3'
services:

  nodejs:
    build: ./

  nginx:
    build: ./nginx
    ports:
      - 80:80

  mysql:
    image: mysql/mysql-server
    restart: always
    environment: 
      ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
      
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    expose:
      - ${REDIS_PORT}
