version: '3'
services:

  mysql:
    image: mysql/mysql-server
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: netflix-clone
    ports: 
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: [ "redis-server" ]
    expose:
      - ${REDIS_PORT}

  nodejs:
    build: ./
    restart: always
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}/tcp
    command: sh -c "pm2-runtime ./pm2.json"
    depends_on: 
      - mysql
      - redis

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - nodejs
      